"use client";

import Sidebar from "@/components/Sidebar";
import "./globals.css";
import { Layout } from "antd";


// export const metadata = {
//   title: "HOS",
//   description: "Generated by Velocity Tech",
// };
const { Header, Content } = Layout;

export default function RootLayout({ children }) {
  console.log("Sidebar:", Sidebar);

  return (
    <html lang="en">
      <head />
      <body>
        <Layout style={{ minHeight: "100vh" }}>
          <Sidebar />
          <Layout style={{ marginLeft: 200 }}>
            <Header style={{ background: "#fff", padding: 0 }} />
            <Content className="p-6 overflow-y-auto bg-gray-50">
              {children}
            </Content>
          </Layout>
        </Layout>
      </body>
    </html>
  );
}
